### ISSUE TITLE
Initial changes

### ISSUE THREAD

**Issue by jaideep777** [jaideep777/jaideep777.github.io#1]
remove slide effect in photo and text
Move text box to the left to not overlap with photo
add contact links to top right menu (currently only in footer)
remove name from top (will change the text box title to name)

**Comment by mandarkbapat** [comment]
OKAy

**Comment by mandarkbapat** [comment]
Removed slide effect in photo and text
Moved text box to the left
Moved contact links to top right menu
Removed name from top
